-- MySQL Script generated by MySQL Workbench
-- Fri Dec  3 14:43:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("p", "i", "g", "d") NOT NULL COMMENT '\"p\" = Pré-incubada\n\"i\" = Incubada\n\"g\" = Graduada\n\"d\" = Desligada',
  `nome_fantasia` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `data_incubacao` DATE NOT NULL,
  `razao_social` VARCHAR(45) NULL,
  `Endereco_id` INT NOT NULL,
  `inscricao_estadual` VARCHAR(15) NOT NULL,
  `cnae` VARCHAR(15) NOT NULL,
  `logo` VARCHAR(45) NULL,
  `comentario` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `razao_social_UNIQUE` (`razao_social` ASC),
  UNIQUE INDEX `nome_fantasia_UNIQUE` (`nome_fantasia` ASC),
  INDEX `fk_Empresa_Endereco1_idx` (`Endereco_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Empresa_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Grupo_id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuário_Grupo1_idx` (`Grupo_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Usuário_Grupo1`
    FOREIGN KEY (`Grupo_id`)
    REFERENCES `mydb`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Colaborador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Empresa_id` INT NOT NULL,
  `Usuário_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Colaborador_Empresa_idx` (`Empresa_id` ASC),
  INDEX `fk_Colaborador_Usuário1_idx` (`Usuário_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Colaborador_Empresa`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Usuário1`
    FOREIGN KEY (`Usuário_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tarefa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Colaborador_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `data_de_inicio` VARCHAR(45) NOT NULL,
  `data_de_fim` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tarefa_Colaborador1_idx` (`Colaborador_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Tarefa_Colaborador1`
    FOREIGN KEY (`Colaborador_id`)
    REFERENCES `mydb`.`Colaborador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `data_de_inicio` DATETIME NOT NULL,
  `dataDeInicio` DATETIME NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_Colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento_has_Colaborador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_Colaborador` (
  `Evento_id` INT NOT NULL,
  `Colaborador_id` INT NOT NULL,
  PRIMARY KEY (`Evento_id`, `Colaborador_id`),
  INDEX `fk_Evento_has_Colaborador_Colaborador1_idx` (`Colaborador_id` ASC),
  INDEX `fk_Evento_has_Colaborador_Evento1_idx` (`Evento_id` ASC),
  CONSTRAINT `fk_Evento_has_Colaborador_Evento1`
    FOREIGN KEY (`Evento_id`)
    REFERENCES `mydb`.`Evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Colaborador_Colaborador1`
    FOREIGN KEY (`Colaborador_id`)
    REFERENCES `mydb`.`Colaborador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permissao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionalidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo_has_Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupo_has_Permissao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grupo_has_Permissao` (
  `Grupo_id` INT NOT NULL AUTO_INCREMENT,
  `Permissao_id` INT NOT NULL,
  PRIMARY KEY (`Grupo_id`, `Permissao_id`),
  INDEX `fk_Grupo_has_Permissao_Permissao1_idx` (`Permissao_id` ASC),
  INDEX `fk_Grupo_has_Permissao_Grupo1_idx` (`Grupo_id` ASC),
  CONSTRAINT `fk_Grupo_has_Permissao_Grupo1`
    FOREIGN KEY (`Grupo_id`)
    REFERENCES `mydb`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Permissao_Permissao1`
    FOREIGN KEY (`Permissao_id`)
    REFERENCES `mydb`.`Permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato_Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contato_Empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contato_Empresa` (
  `id` INT NOT NULL,
  `fax` INT NULL,
  `celular` INT NULL,
  `telefone` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `website` VARCHAR(45) NULL,
  `dominio` VARCHAR(45) NULL,
  `Empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Empresa_id`),
  INDEX `fk_Contato_Empresa_Empresa1_idx` (`Empresa_id` ASC),
  CONSTRAINT `fk_Contato_Empresa_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
